version: '3.7'

networks:
    php-app-network:
        driver: bridge

services:
    php-app-db:
        image: mysql:8.4
        container_name: ${DB_HOST:-php-app-db}
        restart: unless-stopped
        ports:
            - "${DB_PORT:-35506}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-php}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Taipei}
        command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--log-bin", "--binlog-format=ROW"]
        volumes:
            - ./dockerize/data/mysql:/var/lib/mysql
        networks:
            - php-app-network

    php-app-redis:
        image: redis:6.0.20
        container_name: ${REDIS_HOST:-php-app-redis}
        restart: unless-stopped
        ports:
            - "${REDIS_PORT:-35509}:6379"
        volumes:
            - ./dockerize/data/redis:/data
        networks:
            - php-app-network

    php-app-pma:
        image: phpmyadmin/phpmyadmin:5.2
        container_name: php-app-pma
        restart: unless-stopped
        volumes:
            - ./dockerize/conf/phpMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
        ports:
            - "${PMA_PORT:-35510}:80"
        environment:
            SESSION_TIMEOUT: ${PMA_SESSION_TIMEOUT:-86400}
            PMA_HOST: ${DB_HOST:-php-app-db}
            TZ: ${TZ:-Asia/Taipei}
        networks:
            - php-app-network
        depends_on:
            - php-app-db

    php-app-ri:
        image: redislabs/redisinsight:v2
        container_name: php-app-ri
        restart: unless-stopped
        ports:
            - "${RI_PORT:-35520}:5540"
        volumes:
            - ./data/redis_insight:/data
        networks:
            - php-app-network
        depends_on:
            - ${REDIS_HOST:-php-app-redis}

    php-app:
        build:
            context: .
            dockerfile: ./dockerize/dockerfile/app.dockerfile
            args:
                REDIS_VERSION: ${REDIS_VERSION:-6.0.2}
                SWOOLE_VERSION: ${SWOOLE_VERSION:-5.1.2}
                TZ: ${TZ:-Asia/Taipei}
        image: danielhuang030/php-app:0.0.1
        container_name: ${APP:-php-app}
        restart: unless-stopped
        volumes:
            - ./app:/var/www/html/
            - ./dockerize/conf/supervisord/supervisord.conf:/etc/supervisord.conf
            - ./dockerize/conf/php/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
            - ./dockerize/conf/cron/root:/etc/crontabs/root
        networks:
            - php-app-network
        depends_on:
            - ${DB_HOST:-php-app-db}
            - ${REDIS_HOST:-php-app-redis}

    php-app-web-server:
        image: nginx:1.25-alpine
        container_name: php-app-web-server
        restart: unless-stopped
        volumes:
            - ./app:/var/www/html/
            - ./dockerize/log/nginx/:/var/log/nginx/
            - ./dockerize/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${WEB_PORT:-35500}:80"
        networks:
            - php-app-network
